/**
 * doc_generate - Generate and save markdown documents
 * Creates documents in /app/uploads/ for later retrieval
 */
const fs = require('fs').promises;
const path = require('path');

const UPLOADS_DIR = process.env.UPLOADS_DIR || '/app/uploads';

module.exports = {
  definition: {
    type: 'function',
    function: {
      name: 'doc_generate',
      description: 'Generate a markdown document and save it. Use this when the user wants to create a document, write a report, draft content, or generate formatted text that should be saved.',
      parameters: {
        type: 'object',
        properties: {
          title: {
            type: 'string',
            description: 'Document title (used for filename and header)'
          },
          content: {
            type: 'string',
            description: 'Document content in markdown format'
          },
          format: {
            type: 'string',
            enum: ['markdown', 'plain'],
            description: 'Output format (default: markdown)'
          }
        },
        required: ['title', 'content']
      }
    }
  },

  execute: async (args, context) => {
    const { title, content, format = 'markdown' } = args;

    if (!title || !content) {
      return {
        success: false,
        error: 'Title and content are required.',
        type: 'note',
        data: {
          action: 'found',
          message: 'Both title and content are required to generate a document.'
        }
      };
    }

    try {
      // Ensure uploads directory exists
      try {
        await fs.mkdir(UPLOADS_DIR, { recursive: true });
      } catch (err) {
        // Directory may already exist
      }

      // Generate filename from title
      const sanitizedTitle = title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .substring(0, 50);

      const timestamp = Date.now();
      const extension = format === 'plain' ? 'txt' : 'md';
      const filename = `${sanitizedTitle}-${timestamp}.${extension}`;
      const filepath = path.join(UPLOADS_DIR, filename);

      // Build document content
      let documentContent;
      if (format === 'markdown') {
        documentContent = `# ${title}\n\n${content}\n\n---\n*Generated by DeepKit Core on ${new Date().toISOString()}*\n`;
      } else {
        documentContent = `${title}\n${'='.repeat(title.length)}\n\n${content}\n\n---\nGenerated by DeepKit Core on ${new Date().toISOString()}\n`;
      }

      // Save file
      await fs.writeFile(filepath, documentContent, 'utf-8');

      // Get file stats
      const stats = await fs.stat(filepath);
      const sizeKB = Math.round(stats.size / 1024 * 10) / 10;
      const wordCount = content.split(/\s+/).filter(Boolean).length;

      return {
        success: true,
        type: 'note',
        data: {
          action: 'created',
          note: {
            id: `doc-${timestamp}`,
            title: `Document: ${title}`,
            content: `**Document saved successfully.**\n\n**File:** ${filename}\n**Size:** ${sizeKB} KB\n**Words:** ${wordCount}\n**Format:** ${format}\n\n---\n\n**Preview:**\n\n${content.substring(0, 500)}${content.length > 500 ? '...' : ''}`,
            created_at: new Date().toISOString()
          }
        },
        message: `Document "${title}" saved as ${filename} (${wordCount} words)`,
        suggestions: [
          'List my documents',
          'Create another document',
          'Save this as a note'
        ],
        // Extra metadata for potential future use
        metadata: {
          filename,
          filepath,
          format,
          sizeKB,
          wordCount
        }
      };

    } catch (error) {
      return {
        success: false,
        error: `Document generation failed: ${error.message}`,
        type: 'note',
        data: {
          action: 'found',
          note: {
            id: 'error',
            title: 'Error',
            content: `Failed to generate document: ${error.message}`
          }
        }
      };
    }
  }
};
