#!/bin/bash

# =============================================================================
# DEEPKIT - DEVELOPMENT RESET SCRIPT
# =============================================================================
# This script enforces the "DeepKit Sovereign" development environment:
# 1. Stops all containers.
# 2. Resets .env to use 'deepkit123' as the unified password.
# 3. Auto-generates high-entropy keys for security fields.
# 4. Ensures the Docker network exists.
# 5. Starts ALL services (Core + 11 New Modules).
# =============================================================================

set -e # Exit on error

echo "🛑 Stopping all running containers..."
docker compose down --remove-orphans || true

# Check if docker network exists, create if not
if ! docker network ls | grep -q "deepkit-network"; then
    echo "🌐 Creating deepkit-network..."
    docker network create deepkit-network
fi

echo "📝 configuring environment..."
ENV_FILE=".env"

# Function to generate a random 32-byte hex string
generate_key() {
    openssl rand -hex 32
}

# Function to generate a random 64-byte hex string
generate_long_key() {
    openssl rand -hex 64
}

# Create new .env content
cat > "$ENV_FILE" <<EOF
# =============================================================================
# DEEPKIT - ENVIRONMENT VARIABLES (DEV MODE)
# =============================================================================
# Generated by enforce-dev-env.sh
# Unified Password: deepkit123
# =============================================================================

# --- CORE ---
NODE_ENV=development
TIMEZONE=UTC
POSTGRES_USER=deepkit
POSTGRES_PASSWORD=deepkit123
POSTGRES_DB=deepkit

# --- AUTOMATION (n8n) ---
N8N_ENCRYPTION_KEY=$(generate_key)

# --- CMS (Strapi) ---
STRAPI_JWT_SECRET=$(generate_key)
STRAPI_ADMIN_JWT_SECRET=$(generate_key)
STRAPI_APP_KEYS=$(generate_key),$(generate_key),$(generate_key),$(generate_key)

# --- CRM (EspoCRM) ---
MARIADB_ROOT_PASSWORD=deepkit123
ESPOCRM_DB_PASSWORD=deepkit123
ESPOCRM_ADMIN_USERNAME=admin
ESPOCRM_ADMIN_PASSWORD=deepkit123
ESPOCRM_SITE_URL=http://localhost:3004

# --- PASSWORD MANAGER ---
# 64-char hex key for AES-256-GCM
ENCRYPTION_KEY=$(generate_long_key)

# --- MARKETING 360 (Placeholders - User to fill) ---
GEMINI_API_KEY=placeholder_gemini
META_ACCESS_TOKEN=placeholder_meta
LINKEDIN_ACCESS_TOKEN=placeholder_linkedin
TWITTER_API_KEY=placeholder_twitter
TWITTER_API_SECRET=placeholder_twitter_secret
WHATSAPP_PHONE_NUMBER_ID=placeholder_whatsapp_id
WHATSAPP_ACCESS_TOKEN=placeholder_whatsapp_token

# --- AI KEYS (Optional) ---
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
EOF

echo "✅ .env reset with unified password 'deepkit123'"

echo "🧹 Pruning volume data to ensure fresh DB initialization..."
# We need to remove the postgres volume so init-databases.sql runs again
docker volume rm deepkit-store-data || true
# Also remove others to be safe
docker volume rm deepkit-cache-data || true
# Don't remove ollama models (large download)
# docker volume rm deepkit-engine-data || true

echo "🚀 Starting DeepKit Ecosystem..."

# List of modules to start
MODULES=(
    "modules/hub.yml"
    "modules/api-testing.yml"
    "modules/calendar.yml"
    "modules/time-tracker.yml"
    "modules/file-manager.yml"
    "modules/task-tracker.yml"
    "modules/password-manager.yml"
    "modules/marketing360.yml"
    "modules/webhook-manager.yml"
    "modules/invoicing.yml"
    "modules/super-admin.yml"
)

# Build the compose command
COMPOSE_CMD="docker compose -f docker-compose.yml"
for mod in "${MODULES[@]}"; do
    COMPOSE_CMD="$COMPOSE_CMD -f $mod"
done
COMPOSE_CMD="$COMPOSE_CMD up -d --remove-orphans"

echo "Executing: $COMPOSE_CMD"
eval $COMPOSE_CMD

echo "============================================================================="
echo "🎉 DEEPKIT DEPLOYMENT COMPLETE"
echo "============================================================================="
echo "🌍 Main Hub:        http://localhost:7777"
echo "🔑 Unified Pass:    deepkit123"
echo "📡 Super Admin:     http://localhost:7722"
echo "============================================================================="